#pragma once

#define _MW_EQUAL(x, y) __MW_EQUAL(x, y)
#define _MW_NOT_EQUAL(x, y) _MW_NOT(_MW_EQUAL(x, y))

/*--------------------------------------------------
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for _MW_EQUAL
#define __MW_EQUAL_0_0 _MW_CHECK_TRUE
#define __MW_EQUAL_1_1 _MW_CHECK_TRUE
#define __MW_EQUAL_2_2 _MW_CHECK_TRUE
#define __MW_EQUAL_3_3 _MW_CHECK_TRUE
#define __MW_EQUAL_4_4 _MW_CHECK_TRUE
#define __MW_EQUAL_5_5 _MW_CHECK_TRUE
#define __MW_EQUAL_6_6 _MW_CHECK_TRUE
#define __MW_EQUAL_7_7 _MW_CHECK_TRUE
#define __MW_EQUAL_8_8 _MW_CHECK_TRUE
#define __MW_EQUAL_9_9 _MW_CHECK_TRUE
#define __MW_EQUAL_10_10 _MW_CHECK_TRUE
#define __MW_EQUAL_11_11 _MW_CHECK_TRUE
#define __MW_EQUAL_12_12 _MW_CHECK_TRUE
#define __MW_EQUAL_13_13 _MW_CHECK_TRUE
#define __MW_EQUAL_14_14 _MW_CHECK_TRUE
#define __MW_EQUAL_15_15 _MW_CHECK_TRUE
#define __MW_EQUAL_16_16 _MW_CHECK_TRUE
#define __MW_EQUAL_17_17 _MW_CHECK_TRUE
#define __MW_EQUAL_18_18 _MW_CHECK_TRUE
#define __MW_EQUAL_19_19 _MW_CHECK_TRUE
#define __MW_EQUAL_20_20 _MW_CHECK_TRUE
#define __MW_EQUAL_21_21 _MW_CHECK_TRUE
#define __MW_EQUAL_22_22 _MW_CHECK_TRUE
#define __MW_EQUAL_23_23 _MW_CHECK_TRUE
#define __MW_EQUAL_24_24 _MW_CHECK_TRUE
#define __MW_EQUAL_25_25 _MW_CHECK_TRUE
#define __MW_EQUAL_26_26 _MW_CHECK_TRUE
#define __MW_EQUAL_27_27 _MW_CHECK_TRUE
#define __MW_EQUAL_28_28 _MW_CHECK_TRUE
#define __MW_EQUAL_29_29 _MW_CHECK_TRUE
#define __MW_EQUAL_30_30 _MW_CHECK_TRUE
#define __MW_EQUAL_31_31 _MW_CHECK_TRUE
#define __MW_EQUAL_32_32 _MW_CHECK_TRUE
#define __MW_EQUAL_33_33 _MW_CHECK_TRUE
#define __MW_EQUAL_34_34 _MW_CHECK_TRUE
#define __MW_EQUAL_35_35 _MW_CHECK_TRUE
#define __MW_EQUAL_36_36 _MW_CHECK_TRUE
#define __MW_EQUAL_37_37 _MW_CHECK_TRUE
#define __MW_EQUAL_38_38 _MW_CHECK_TRUE
#define __MW_EQUAL_39_39 _MW_CHECK_TRUE
#define __MW_EQUAL_40_40 _MW_CHECK_TRUE
#define __MW_EQUAL_41_41 _MW_CHECK_TRUE
#define __MW_EQUAL_42_42 _MW_CHECK_TRUE
#define __MW_EQUAL_43_43 _MW_CHECK_TRUE
#define __MW_EQUAL_44_44 _MW_CHECK_TRUE
#define __MW_EQUAL_45_45 _MW_CHECK_TRUE
#define __MW_EQUAL_46_46 _MW_CHECK_TRUE
#define __MW_EQUAL_47_47 _MW_CHECK_TRUE
#define __MW_EQUAL_48_48 _MW_CHECK_TRUE
#define __MW_EQUAL_49_49 _MW_CHECK_TRUE
#define __MW_EQUAL_50_50 _MW_CHECK_TRUE
#define __MW_EQUAL_51_51 _MW_CHECK_TRUE
#define __MW_EQUAL_52_52 _MW_CHECK_TRUE
#define __MW_EQUAL_53_53 _MW_CHECK_TRUE
#define __MW_EQUAL_54_54 _MW_CHECK_TRUE
#define __MW_EQUAL_55_55 _MW_CHECK_TRUE
#define __MW_EQUAL_56_56 _MW_CHECK_TRUE
#define __MW_EQUAL_57_57 _MW_CHECK_TRUE
#define __MW_EQUAL_58_58 _MW_CHECK_TRUE
#define __MW_EQUAL_59_59 _MW_CHECK_TRUE
#define __MW_EQUAL_60_60 _MW_CHECK_TRUE
#define __MW_EQUAL_61_61 _MW_CHECK_TRUE
#define __MW_EQUAL_62_62 _MW_CHECK_TRUE
#define __MW_EQUAL_63_63 _MW_CHECK_TRUE
#define __MW_EQUAL_64_64 _MW_CHECK_TRUE

#define __MW_EQUAL(x, y) _MW_CHECK(__MW_EQUAL_##x##_##y)
