#pragma once

#define _MINIWIN_EQUAL(x, y) __MINIWIN_EQUAL(x, y)
#define _MINIWIN_NOT_EQUAL(x, y) _MINIWIN_NOT(_MINIWIN_EQUAL(x, y))

/*--------------------------------------------------
*            Internal macros(Dont use!)             |
---------------------------------------------------*/

// Internal for _MINIWIN_EQUAL
#define __MINIWIN_EQUAL_0_0 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_1_1 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_2_2 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_3_3 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_4_4 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_5_5 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_6_6 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_7_7 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_8_8 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_9_9 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_10_10 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_11_11 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_12_12 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_13_13 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_14_14 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_15_15 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_16_16 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_17_17 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_18_18 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_19_19 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_20_20 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_21_21 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_22_22 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_23_23 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_24_24 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_25_25 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_26_26 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_27_27 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_28_28 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_29_29 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_30_30 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_31_31 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_32_32 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_33_33 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_34_34 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_35_35 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_36_36 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_37_37 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_38_38 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_39_39 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_40_40 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_41_41 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_42_42 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_43_43 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_44_44 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_45_45 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_46_46 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_47_47 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_48_48 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_49_49 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_50_50 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_51_51 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_52_52 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_53_53 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_54_54 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_55_55 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_56_56 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_57_57 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_58_58 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_59_59 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_60_60 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_61_61 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_62_62 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_63_63 _MINIWIN_CHECK_TRUE
#define __MINIWIN_EQUAL_64_64 _MINIWIN_CHECK_TRUE

#define __MINIWIN_EQUAL(x, y) _MINIWIN_CHECK(__MINIWIN_EQUAL_##x##_##y)
